version: "3.8"
services:
    ansible:
        build:
            context: ./dockerfiles/ansible
            dockerfile: Dockerfile
            args:
              USER_NAME: ${SERVICE_ANSIBLE_USER}
              USER_UID: ${SERVICE_ANSIBLE_UID}
              GROUP_NAME: ${SERVICE_ANSIBLE_GROUP}
              GROUP_GID: ${SERVICE_ANSIBLE_GID}
              USER_PASSWORD: ${SERVICE_ANSIBLE_PASSWORD}
        environment:
            - GCP_PROJECT=${GCP_PROJECT}
            - GCP_AUTH_KIND=${GCP_AUTH_KIND}
            - GCP_SERVICE_ACCOUNT_FILE=${SERVICE_ANSIBLE_GCP_SERVICE_ACCOUNT_FILE}
            - BEANSTALK_USERNAME=${BEANSTALK_USERNAME}
            - BEANSTALK_ACCESS_TOKEN=${BEANSTALK_ACCESS_TOKEN}
            - TEMPORARY_DIRECTORY=${SERVICE_ANSIBLE_TEMPORARY_DIRECTORY}
            - GITHUB_APP_PRIVATE_KEY_FILE=${SERVICE_ANSIBLE_GITHUB_APP_PRIVATE_KEY_FILE}
            - GITHUB_APP_ID=${SERVICE_ANSIBLE_GITHUB_APP_ID}
            - GITHUB_APP_INSTALLATION_ID=${SERVICE_ANSIBLE_GITHUB_APP_INSTALLATION_ID}
            - BEANSTALK_PRIVATE_KEY_FILE=${SERVICE_ANSIBLE_BEANSTALK_PRIVATE_KEY_FILE}
            - GITHUB_PRIVATE_KEY_FILE=${SERVICE_ANSIBLE_GITHUB_PRIVATE_KEY_FILE}
        volumes:
          - ${SERVICE_ANSIBLE_TEMPORARY_DIRECTORY}
          - ${HOST_GITHUB_APP_PRIVATE_KEY_FILE}:${SERVICE_ANSIBLE_GITHUB_APP_PRIVATE_KEY_FILE}
          - ${HOST_BEANSTALK_PRIVATE_KEY_FILE}:${SERVICE_ANSIBLE_BEANSTALK_PRIVATE_KEY_FILE}
          - ${HOST_GITHUB_PRIVATE_KEY_FILE}:${SERVICE_ANSIBLE_GITHUB_PRIVATE_KEY_FILE}
          - ${HOST_GCP_SERVICE_ACCOUNT_FILE}:${SERVICE_ANSIBLE_GCP_SERVICE_ACCOUNT_FILE}
