version: "3.8"
services:
    ansible:
        build:
            context: ./dockerfiles/ansible
            dockerfile: Dockerfile
        environment:
            - GCP_PROJECT=${GCP_PROJECT}
            - GCP_AUTH_KIND=${GCP_AUTH_KIND}
            - GCP_SERVICE_ACCOUNT_FILE=${SERVICE_ANSIBLE_GCP_SERVICE_ACCOUNT_FILE}
            - ANSIBLE_VAULT_PASSWORD_FILE=${SERVICE_ANSIBLE_VAULT_PASSWORD_FILE}
        volumes:
          - ${HOST_GCP_SERVICE_ACCOUNT_FILE}:${SERVICE_ANSIBLE_GCP_SERVICE_ACCOUNT_FILE}
          - ${HOST_ANSIBLE_VAULT_PASSWORD_FILE}:${SERVICE_ANSIBLE_VAULT_PASSWORD_FILE}
